# Development Profile
spring.config.activate.on-profile=dev

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/centsibility_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.centsibility=DEBUG
